### PR TITLE
Add 9.0 patch

### PR DESCRIPTION
**Pull request by Zackptg5**
Resubmitted, will automatically disable reflink if progress bar is used

### CODE REVIEW

**Comment by jarun** [comment]
Thank you!

**Comment by whalehub** [comment]
@Zackptg5 Just to clarify, does reflink still work if one invokes advcp without `-g`?

**Comment by Zackptg5** [comment]
@whalehub ya, I only auto disable reflink if the progress bar option is specified

**Comment by whalehub** [comment]
@Zackptg5 Thanks for the clarification!

**Comment by jarun** [comment]
@Zackptg5 can you please dociment this?

**Comment by harriott** [comment]
(no Issues tab so reporting here, as Jarun advised)
1) Arch linux: I only get progress bar when using `cpg -g`, `mvg -g` only ever shows size calculations.
2) If source filename contains a single quote, `mvg -g` succeeds, but the progress calculation fails completely.

**Comment by jarun** [comment]
@Zackptg5 in `do_move()`, why are we not calculating `du` for each file?

**Comment by jarun** [comment]
Ignore the question. The comment on latest is wrong.

**Comment by harriott** [comment]
`mvg -g` has somehow been slightly improved in that a progress bar is now shown, but always at 100% (ie not really showing the progress)...

**Comment by SlrG** [comment]
This is a "problem" of the newer coreutils versions. They introduced usage of the "copy_file_range" system call. If available on a system it is used instead of the internal method used before. 

For this in-kernel copy process its only possible to update the progress bar, whenever it finishes copying a file. Thus the per file copy bar is always full and only the global progress bar shows the progress.

In the end this new method causes a huge loss of information and there is probably no chance to bring it back.

Falling back to the internal copy mechanism whenever the progress parameter is used, might not be the best idea, as the new method wasn't introduced without reasons. 
 
An alternative to the always full file progress bar, could be to disable it, whenever the new copy mechanism is used.

**Pull request merged**
